"""
Django settings for aroundlb project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

# --------------------------------------------------
# Imports
# --------------------------------------------------

import os

# --------------------------------------------------
# Project settings
# --------------------------------------------------

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
ASSETS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ocw3^2w6z!@b8vn2@b-3zvxb)rk(7ns=wy0cw6ucub2z5uz2vm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ROOT_URLCONF = 'aroundlb.urls'

# --------------------------------------------------
# Apps settings
# --------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CUSTOM_APPS = [
    'core',
    'djcelery',
    'django_extensions',
]

INSTALLED_APPS += CUSTOM_APPS

# --------------------------------------------------
# Middleware settings
# --------------------------------------------------

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------
# WSGI settings
# --------------------------------------------------

WSGI_APPLICATION = 'aroundlb.wsgi.application'

# --------------------------------------------------
# AWS settings
# --------------------------------------------------

S3_URL_BASE = 'http://aroundlb.s3-website-us-east-1.amazonaws.com'

# --------------------------------------------------
# Media settings
# --------------------------------------------------

ALLOWED_EXTENSIONS = ['jpg', 'tif', 'psd', 'psb', 'png', 'gif', 'mp4', 'mov', 'avi', 'dng', 'arw', 'crw', 'cr2']
ENABLED_EXTENSIONS = ['jpg', 'tif', 'png', 'dng']

IMAGEMAGICK_PATH = '/usr/local/bin/'
PREVIEW_SIZE = (512, 512)
PREVIEW_QUALITY = 80

PREVIEW_UPDATE_ON_SAVE = True
METADATA_UPDATE_ON_SAVE = True
ASSET_AUTO_SAVE = True

EXIFTOOL_PATH = '/usr/local/bin/exiftool'

KRPANO_DIR = os.path.join(PROJECT_DIR, 'krpano')
KRPANO_BIN = os.path.join(KRPANO_DIR, 'bin/osx', 'krpano')
KRPANO_TEMPLATE = os.path.join(KRPANO_DIR, 'multires.config')


# --------------------------------------------------
# Template settings
# --------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'core/templates'),
                 os.path.join(BASE_DIR, 'crunchy/templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_settings',
            ],
        },
    },
]


# --------------------------------------------------
# Media files settings
# --------------------------------------------------

MEDIA_ROOT = os.path.join(PROJECT_DIR, 'media')
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)

MEDIA_URL = "/media/"


# --------------------------------------------------
# Static files settings
# --------------------------------------------------

STATIC_ROOT = os.path.join(PROJECT_DIR, 'static_run')
if not os.path.exists(STATIC_ROOT):
    os.makedirs(STATIC_ROOT)

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'core/static'),
    ]
for static_dir in STATICFILES_DIRS:
    if not os.path.exists(static_dir):
        os.makedirs(static_dir)


# --------------------------------------------------
# Database settings
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
# --------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'aroundlb.sqlite3'),
    }
}

# --------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --------------------------------------------------
# Celery Settings
# --------------------------------------------------

BROKER_URL = 'redis://localhost:6379/0'
BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'

# --------------------------------------------------
# Cache Settings
# --------------------------------------------------

CACHE_MIDDLEWARE_ALIAS = 'default'

# --------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# --------------------------------------------------
# Settings loader
# --------------------------------------------------

try:
    app_stage = os.environ['DJANGO_APP_STAGE']
except:
    app_stage = 'dev'

if app_stage == 'prod':
    from settings_prod import *
elif app_stage == 'dev':
    from settings_dev import *