# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('file_path', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('file_path_md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('preview', models.ImageField(blank=True, height_field='preview_height', max_length=256, null=True, upload_to='previews/', width_field='preview_width')),
                ('preview_width', models.IntegerField(blank=True, db_index=True, null=True)),
                ('preview_height', models.IntegerField(blank=True, db_index=True, null=True)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['-datetime_updated'],
                'get_latest_by': 'datetime_updated',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='core.Asset')),
                ('content', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'datetime_updated',
            },
        ),
    ]
