# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('original', models.ImageField(blank=True, height_field='original_height', max_length=256, null=True, upload_to='originals/', width_field='original_width')),
                ('original_width', models.IntegerField(blank=True, db_index=True, null=True)),
                ('original_height', models.IntegerField(blank=True, db_index=True, null=True)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('title', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ['-datetime_updated'],
                'get_latest_by': 'datetime_updated',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('content', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'datetime_updated',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='core.Metadata'),
        ),
    ]
