# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Asset')),
                ('title', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'datetime_updated',
            },
            bases=('core.asset',),
        ),
    ]
