# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('title', models.TextField(blank=True, help_text='Displayable title', null=True)),
                ('name', models.CharField(db_index=True, help_text='Unique name for this object', max_length=255, unique=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['-datetime_updated'],
                'get_latest_by': 'datetime_updated',
            },
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='md5',
            new_name='original_md5',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_index=True, default=1, help_text='Unique name for this object', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='panorama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.Panorama'),
            preserve_default=False,
        ),
    ]
