# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160401_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.Panorama'),
        ),
    ]
