# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160401_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True),
        ),
        migrations.AddField(
            model_name='panorama',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True),
        ),
    ]
