# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160401_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='panorama',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
