# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160402_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='datetime_created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
